// libs/website/ui/src/lib/common/email-address/email-address.component.tsx
import styles from './email-address.module.scss';
import Hyperlink from '../hyperlink/hyperlink.component';

interface Props {
  className?: string;
}

export default function EmailAddress(props: Props): JSX.Element {
  return (
    <Hyperlink
      href="mailto:dark@darkrush.photo?subject=Dark Rush Photography"
      text="dark@darkrus.photo"
      className={props.className ? styles[props.className] : ''}
    />
  );
}

// tools/migration/libs/website/ui/src/lib/common/email-address/email-address.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'drp-email-address',
  templateUrl: './email-address.component.html',
  styleUrls: ['./email-address.component.scss'],
})
export class EmailAddressComponent {}

<drp-hyperlink
  url="mailto: dark@darkrush.photo?subject=Dark Rush Photography"
  text="dark@darkrush.photo"
></drp-hyperlink>
